# Python Modules : NumPy

NumPy was created in 2005 by Travis Oliphant written in Python, C/C++.

NumPy or "Numerical Python"  is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
# importing NumPy
import numpy as np
#Checking NumPy Version
print(np.__version__)

1.21.5


# Why Use NumPy?

Python lists serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

*Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

# 4.1.1 Create a NumPy array

In [4]:
#We can create a NumPy ndarray object by using the array() function.
import numpy
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

NumPy is usually imported under the np alias (alternate name) import numpy as np

In [2]:
import numpy as np
t=(1, 2, 3, 4, 5.5)
#We can create a NumPy ndarray with a tuple
arr = np.array(t)

print(arr)

[1.  2.  3.  4.  5.5]


# 4.1.2 Dimensions in Arrays

In [15]:
import numpy as np

a = np.array(42) # 0-D Arrays
b = np.array([1, 2, 3, 4, 5]) # 1-D Arrays
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D Arrays
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3-D Arrays

In [14]:
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# Higher Dimensional Arrays

In [17]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

# 4.1.3 Access Array Elements

In [21]:
import numpy as np

arr = np.array([10, 2, 3, 4])

print(arr[0])
print(arr[2] + arr[3])

10
7


Access 2-D Arrays

In [1]:
import numpy as np

arr = np.array([[1,200,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  200
5th element on 2nd row:  10


Access 3-D Arrays

In [11]:
# Access the third element of the second array of the first array:
import numpy as np

arr = np.array([
                [[1, 2, 3], [4, 5, 60]],
                [[7, 8, 9], [10, 11, 12]],
                [[7, 8, 9], [10, 11, 120]],
               ])
print(arr)
print(arr[2, 1, 2])

[[[  1   2   3]
  [  4   5  60]]

 [[  7   8   9]
  [ 10  11  12]]

 [[  7   8   9]
  [ 10  11 120]]]
120


# Negative Indexing

In [3]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,100]])
print('Last element from 2nd dim: ', arr[1, 4])
print('Last element from 2nd dim: ', arr[1, -1])
print('Last element from 2nd dim: ', arr[-1, -1])

Last element from 2nd dim:  100
Last element from 2nd dim:  100
Last element from 2nd dim:  100


# 4.1.4 Slicing arrays

Syntax : [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [4]:
import numpy as np
l=[10, 20, 30, 40, 50, 60, 70]
arr = np.array(l)

print(arr[1:5])

[20 30 40 50]


The result includes the start index, but excludes the end index.

In [5]:
l=[10, 20, 30, 40, 50, 60, 70]
# Slice elements from index 4 to the end of the array:
print(arr[4:])
# Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[50 60 70]
[10 20 30 40]


# 4.1.4.1 Negative Slicing

In [38]:
# Slice from the index 3 from the end to index 1 from the end:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) # start:end

[5 6]


In [13]:
#Use the step value to determine the step of the slicing:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) # start:end:step
print(arr[-5:-2:2]) # start:end:step

[2 4]
[3 5]


In [6]:
# Return every other element from the entire array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[ : :2])# start:end:step

[1 3 5 7]


# 4.1.4.2 Slicing 2-D Arrays

In [43]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr)
print(arr[1, 1:4]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [46]:
#From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) # row, col

[3 8]


In [51]:
"""From both elements, slice index 1 to index 4 (not included), 
this will return a 2-D array:"""

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# 4.1.5 NumPy Data Types : ob.astype()

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

# 4.1.5.1 Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [18]:
#Create an array with data type 4 bytes (32 bit) integer:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i8') #  change to : dtype='i8'

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


# 5.1.5.2 Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [9]:
#Change data type from float to integer by using 'i' as parameter value:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
#arr=int(arr)

#newarr = arr.astype(bool)
#newarr = arr.astype('i') # a string, like 'f' for float, 'i' for integer etc
newarr = arr.astype('int') # float for float and int for integer.
#arr = np.array(newarr, dtype='i8') #  change to : dtype='i8'


print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# 5.1.6.1  NumPy Array Shape

In [13]:
# Print the shape of a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [14]:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# 5.1.6.2 NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

Reshape From 1-D to 2-D

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Reshape From 1-D to 3-D

In [21]:
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#  5.1.6.3  Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

#related operations - flatten, ravel,rot90, flip, fliplr, flipud

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# 5.1.7 numpy.arange() in Python
The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop) 

In [17]:
# numpy.arange method
 
import numpy as geek
 
print("A\n", geek.arange(4).reshape(2, 2), "\n")
print("A\n", geek.arange(4, 10), "\n")
print("A\n", geek.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



The advantage of numpy.arange() over the normal in-built range() function is that it allows us to generate sequences of numbers that are not integers.

In [1]:
# numpy.arange method
 
import numpy as np
 
# Printing all numbers from 1 to
# 2 in steps of 0.1
print(np.arange(1, 2, 0.1))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [15]:
#a=int(arr) #produce error

# 5.1.7.1  NumPy Array Iterating

In [35]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [36]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


# 5.1.8 NumPy Array Copy vs View
The copy is a new array, and the view is just a view of the original array.

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
#Every NumPy array has the attribute base that returns None if the array owns the data.
#Otherwise, the base  attribute refers to the original object.
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# 8.1.9 Joining NumPy Array

In [23]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Joining 2-D array

In [24]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1.shape)

(2, 2)


Join two 2-D arrays along column (axis=0):

In [26]:
arr = np.concatenate((arr1, arr2))

print(arr.shape)
print(arr)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Join two 2-D arrays along rows (axis=1):

In [24]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [26]:
arr = np.concatenate((arr1, arr2), axis=1)
print(arr.shape)
print(arr)

(2, 4)
[[1 2 5 6]
 [3 4 7 8]]


Joining Arrays Using Stack Functions

In [28]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#NumPy provides a helper function: hstack() to stack along rows.
arr = np.hstack((arr1, arr2))

#NumPy provides a helper function: vstack()  to stack along columns.
arr = np.vstack((arr1, arr2))

#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# 5.1. 10 Splitting NumPy Arrays

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# 5.1.11 Searching Arrays
To search an array, use the where() method.

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


# 5.1.12 NumPy Sorting Arrays

In [33]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [34]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# 5.1. 13  Filter 

In [53]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [54]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
