# scikit-learn ( sklearn ) : Machine Learning in Python)
Scikit-learn (formerly scikits.learn and also known as sklearn) is a free software machine learning library for the Python programming language.


It features various classification, regression and clustering algorithms, and reusable in various contexts.

Simple and efficient tools for predictive data analysis.

Built on NumPy, SciPy, and matplotlib.

In [59]:
#!pip install scikit-learn

In [95]:
import sklearn

# Preprocessing
Feature extraction and normalization.

Applications: Transforming input data such as text for use with machine learning algorithms.

Algorithms: preprocessing, feature extraction, and more...

The sklearn.preprocessing package provides several common utility functions and transformer classes to change raw feature vectors into a representation that is more suitable for the downstream estimators.

In [96]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [101]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,auc

In [102]:
df=pd.read_csv('iris.csv')
#df=df.drop('Unnamed:0',axis=1,inplace=True)
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
145      2  
146      2  
147      2  
148      2  
149      2

In [64]:
df.shape

(150, 5)

In [105]:
X=df.drop('class',axis=1) #row:  axis=0 ; column: axis=1
y=df['class']
#print(X)
#print(y)

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2, random_state=42)

In [75]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(type(X_train))
print(X_train.head())

(120, 4)
(30, 4)
(120,)
(30,)
<class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4
11                4.8               3.4                1.6               0.2
42                4.4               3.2                1.3               0.2


In [114]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
#min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler = MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
print(type(X_train))
#print(X_train)

<class 'numpy.ndarray'>


In [115]:
X_test = min_max_scaler.fit_transform(X_test)
#print(X_test)

In [84]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [85]:
model = SVC() 
model.fit(X_train, y_train) # Training the model

LogisticRegression()

In [87]:
y_pred = model.predict(X_test)

In [88]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [89]:
y_test

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: class, dtype: int64

In [116]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,auc
cm = confusion_matrix(y_test, y_pred) 
print ("Confusion Matrix : \n", cm) 

Confusion Matrix : 
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]


In [92]:
from sklearn.metrics import accuracy_score,classification_report 
print ("Accuracy : ", accuracy_score(y_test, y_pred)) 

Accuracy :  0.9666666666666667


In [94]:
print(classification_report(y_test, y_pred)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
pipe = make_pipeline(StandardScaler(), LogisticRegression())
# apply scaling on training data
pipe.fit(X_train, y_train)  
Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])
 # apply scaling on testing data, without leaking training data.
pipe.score(X_test, y_test) 