# Feature Engineering in Python

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
c=['BAN','PAK','SRI','IND']

In [39]:
data=pd.DataFrame({'country':c})

In [40]:
data

country
0     BAN
1     PAK
2     SRI
3     IND

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le=LabelEncoder()

In [43]:
data['country_e']=le.fit_transform(data.country)

In [44]:
data

country  country_e
0     BAN          0
1     PAK          2
2     SRI          3
3     IND          1

In [45]:
#data.drop(['country'], axis=1)

In [46]:
from sklearn.preprocessing import OneHotEncoder

In [47]:
 enc = OneHotEncoder(handle_unknown='ignore')

In [48]:
df=pd.DataFrame(enc.fit_transform(data[['country_e']]).toarray())

In [49]:
df

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  0.0  1.0  0.0
2  0.0  0.0  0.0  1.0
3  0.0  1.0  0.0  0.0

In [50]:
df=df.drop(0, axis=1)
df

1    2    3
0  0.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0

In [29]:
enc.fit_transform(data[['country_e']]).toarray()

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [ ]:
data

In [ ]:
print(type(data))

In [ ]:
a=['20','24','22','23']

In [ ]:
data['age']=a

In [ ]:
data

In [51]:
#2.OneHotEncoder : New Style 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Country column
ct = ColumnTransformer([("country", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(data)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 2.]
 [0. 0. 0. 1. 3.]
 [0. 1. 0. 0. 1.]]


In [52]:
X=X[:,1:]
print(X)

[[0. 0. 0. 0.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]
 [1. 0. 0. 1.]]
